# Generated by Django 3.2.7 on 2022-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er_id', models.IntegerField()),
                ('er_code', models.CharField(max_length=15)),
                ('er_display_text', models.CharField(max_length=50)),
                ('er_min_no', models.IntegerField()),
                ('er_max_no', models.IntegerField()),
            ],
        ),
    ]
