# Generated by Django 3.2.7 on 2022-04-26 14:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('er_code', models.CharField(max_length=15)),
                ('er_display_text', models.CharField(max_length=50)),
                ('er_min_no', models.IntegerField()),
                ('er_max_no', models.IntegerField()),
                ('er_created_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('er_updated_timestamp', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Range Custom Name',
                'verbose_name_plural': 'Employee Range Custom Name Plural',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.employeerange')),
            ],
        ),
    ]
