# Generated by Django 3.2.7 on 2022-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(to='common.EmployeeRange')),
            ],
        ),
    ]
